on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN }}
          title: 'Issue'
          body: 'Body'
          assignees: 'ShockwaVee'
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: 'Davor'
      - run: |
          echo "Time: ${{steps.hello.outputs.time}}"
          echo $HELLO
          echo ${{ steps.issue.outputs.issue }}
