name: Create release branch

on:
  workflow_dispatch

jobs:
  create-release-branch:
    name: Create the release branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'AB-123'
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Generate the release messages
        id: release-message
        run: |
          ls
          pwd
          cd bin/
          ls
          echo "$(node ./test.js)" >> $GITHUB_PATH
        
      - name: Create Pull Request
        env: 
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          current_date=$(date +'%d %b %Y')
          version_number=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                               --header "Accept: application/vnd.github.v3+json" \
                               "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
                               | jq -r '.tag_name' | sed -E 's/r([0-9]{3}).*/\1/')
          git checkout -b "release/${version_number}"
          git push origin "release/${version_number}"
          gh pr create --title "release: $current_date" --body "$(<${GITHUB_PATH})" --base main
