name: Create release branch

on:
  workflow_dispatch

jobs:
  create-release-branch:
    name: Create the release branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Generate the release messages
        id: releaseMessage
        run: echo "::set-output name=output::$(node ./bin/test.js)"
      - name: Create Pull Request
        env: 
          GITHUB_TOKEN: ${{secrets.PAT}}
        run: |
          gh pr create --title "release: ${{steps.get-latest-tag.outputs.tag}}" --body "${{steps.releaseMessage.outputs.output}}" --base main --head AB-123
          
