name: Create release branch

on:
  workflow_dispatch

jobs:
  create-release-branch:
    name: Create the release branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'AB-123'
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Get Latest Release Tag
        id: latest_release
        run: |
          response=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       --header "Accept: application/vnd.github.v3+json" \
                       "https://api.github.com/repos/${{ github.repository }}/releases/latest")

          echo "latest_tag=$(echo "${response}" | jq -r '.tag_name')" >> $GITHUB_ENV
          
      - name: Increment Version Number
        id: increment_version
        run: |
          version_number=$(echo "${{ env.latest_tag }}" | sed -E 's/r([0-9]{3}).*/\1/')
          next_version_number=$((version_number + 1))
          echo "next_version_number=${next_version_number}" >> $GITHUB_ENV
          
      - name: Create a new branch
        run: |
          git checkout -b "release/${{ env.next_version_number }}"
          git push origin "release/${{ env.next_version_number }}"
          
      - name: Generate the release messages
        id: release-message
        run: |
          git fetch origin main:refs/remotes/origin/main
          git diff --name-only "release/${{env.next_version_number}}..origin/main"
          echo "$(node ./bin/test.js)" >> $GITHUB_PATH
        
      - name: Create Pull Request
        env: 
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          current_date=$(date +'%d %b %Y')
          gh pr create --title "release: $current_date" --body "$(<${GITHUB_PATH})" --base main --assignee "ShockwaVee"
