name: Create release branch

on:
  workflow_dispatch

jobs:
  create-release-branch:
    name: Create the release branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'AB-123'
      - name: Get Latest Release Tag
        id: latest_release
        run: |
          # Make API request to retrieve release data
          response=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       --header "Accept: application/vnd.github.v3+json" \
                       "https://api.github.com/repos/${{ github.repository }}/releases/latest")

          # Extract the latest tag from the response
          tag=$(echo "${response}" | jq -r '.tag_name')

          # Set the output for the latest tag
          echo "::set-output name=latest_tag::${tag}"
      - name: Get the version number
        id: version-number
        run: |
          input="${{ steps.latest_release.outputs.latest_tag }}"
          echo "::set-output name=version-number::$(echo "$input" | sed -E 's/r([0-9]{3}).*/\1/')"
      - name: Create a new branch
        run: |
          git checkout -b release/${{steps.version-number.outputs.version-number}}
          git push origin release/${{steps.version-number.outputs.version-number}}
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Generate the release messages
        id: release-message
        run: echo "::set-output name=output::$(node ./bin/test.js)"
      - name: Create Pull Request
        env: 
          GITHUB_TOKEN: ${{secrets.PAT}}
        run: |
          gh pr create --title "release: ${{steps.version-number.outputs.version-number}}" --body "${{steps.release-message.outputs.output}}" --base main --head AB-123
          
