name: Create release branch

on:
  workflow_dispatch

jobs:
  create-release-branch:
    name: Create the release branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Create a new branch
        run: |
          git branch release/111
          git push
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Generate the release messages
        id: releaseMessage
        run: echo "::set-output name=output::$(node ./bin/test.js)"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          title: 'release: TODO DATE'
          body: ${{steps.releaseMessage.outputs.output}}
          assignees: 'ShockwaVee'
          base: 'AB-123'
          branch: 'release/111'
          
