# This is a basic workflow to help you get started with Actions

name: types

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: decimal
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: bornfight/maboo-backend
          token: ${{ secrets.PAT }}
          path: maboo-backend
      - uses: actions/checkout@master
        with:
          path: maboo-frontend
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          cd maboo-backend
          composer install --prefer-dist --no-progress --no-suggest
      - name: Run a multi-line script
        run: |
          ls
          cd maboo-backend
          ls
      - name: Run a multi-line script
        run: |
          ls
          cd maboo-frontend
          yarn install --frozen-lockfile
      - name: Run a multi-line script
        run: |
          cd maboo-frontend
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: ./maboo-frontend
          token: ${{ secrets.PAT }}
          body: "Most recent update of graphQL types. If there are any linter errors, fetch the branch locally and fix any errors."
          assignees: ShockwaVee
          reviwers: ShockwaVee
          title: "feat/update-types"
